### ISSUE TITLE
Joypad implementation.

### ISSUE THREAD

**Issue by ricardoalcantara** [godot-mega-man/Mega-Man-Engine#1]
Very nice game! I would love to have a joypad implementation!
I cloned this repo and setup the input map this way
![image](https://user-images.githubusercontent.com/2466466/62426067-75502300-b6b6-11e9-9d80-b89d1cff117d.png)

I tested on linux and worked just fine!

**Comment by Firstject** [comment]
Definitely a good idea to add this!

**Comment by HeartCodeGames** [comment]
Here are the keys I've mapped. I also made game_jump key using **PS Cross, Xbox A, Nintendo B** key instead of D-pad up. And using **PS Square, Xbox X, Nintendo Y** for game_action key. Please consider this as a default setting.
![GodotSampleKeys](https://user-images.githubusercontent.com/48884170/62456638-15837600-b7a3-11e9-9195-1a165eed7268.png)
